name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  github-token:
    description: 'Github token'
    required: true
    default: 'World'
outputs:
  time:
    description: 'The time we greeted you'
runs:
  using: 'node16'
  main: 'index.js'
